# CMake generated Testfile for 
# Source directory: /Users/joaquin/git/entangled-develop/cclient
# Build directory: /Users/joaquin/git/entangled-develop/cbuild/cclient
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_add_neighbors "test_add_neighbors")
set_tests_properties(test_add_neighbors PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;168;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_attach_to_tangle "test_attach_to_tangle")
set_tests_properties(test_attach_to_tangle PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;169;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_broadcast_transactions "test_broadcast_transactions")
set_tests_properties(test_broadcast_transactions PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;170;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_check_consistency "test_check_consistency")
set_tests_properties(test_check_consistency PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;171;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_find_transactions "test_find_transactions")
set_tests_properties(test_find_transactions PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;172;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_balances "test_get_balances")
set_tests_properties(test_get_balances PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;173;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_inclusion_states "test_get_inclusion_states")
set_tests_properties(test_get_inclusion_states PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;174;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_neighbors "test_get_neighbors")
set_tests_properties(test_get_neighbors PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;175;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_node_info "test_get_node_info")
set_tests_properties(test_get_node_info PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;176;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_tips "test_get_tips")
set_tests_properties(test_get_tips PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;177;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_transactions_to_approve "test_get_transactions_to_approve")
set_tests_properties(test_get_transactions_to_approve PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;178;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_get_trytes "test_get_trytes")
set_tests_properties(test_get_trytes PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;179;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_remove_neighbors "test_remove_neighbors")
set_tests_properties(test_remove_neighbors PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;180;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_store_transactions "test_store_transactions")
set_tests_properties(test_store_transactions PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;181;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
add_test(test_were_addresses_spent_from "test_were_addresses_spent_from")
set_tests_properties(test_were_addresses_spent_from PROPERTIES  _BACKTRACE_TRIPLES "/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;165;add_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;182;add_cclient_test;/Users/joaquin/git/entangled-develop/cclient/CMakeLists.txt;0;")
